# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# CENTOS_IMAGE
# CI_COMMIT_TAG
# DOCKER_IMAGE
# DIND
# DOCKER_USER
# DOCKER_PASS
# REGISTRY
# ORG

services:
  - ${DIND}

stages:
  - build
  - package

silo-build:
  image: $SEED_COMMON:$CI_COMMIT_TAG
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir -p $GOPATH/src/github.com/ngageoint
    - ln -s $(pwd) $GOPATH/src/github.com/ngageoint/seed-silo
    - cd $GOPATH/src/github.com/ngageoint/seed-silo
    - go build -o silo main.go
  only:
    - tags

silo-package:
  image: ${DOCKER_IMAGE}
  stage: package
  dependencies:
    - silo-build
  script:
    - docker login -u $DOCKER_USER -p "$DOCKER_PASS" $REGISTRY
    - docker build --label $CI_COMMIT_TAG --build-arg IMAGE=$SEED_COMMON:$CI_COMMIT_TAG . -t $REGISTRY/$ORG/seed-silo:$CI_COMMIT_TAG
    - docker push $REGISTRY/$ORG/seed-silo:$CI_COMMIT_TAG
  only:
    - tags
