# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# CENTOS_IMAGE
# CI_COMMIT_TAG
# DOCKER_IMAGE
# DIND
# $CI_BUILD_TOKEN
# REGISTRY
# ORG

variables:
  IMAGE_PREFIX: "silo"

services:
  - ${DIND}

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY

stages:
  - build
  - package

silo-build:
  image: ${DOCKER_IMAGE}
  stage: build
  artifacts:
    untracked: true
  script:
    - go build -o silo main.go
  only:
    - master
    - tags

silo-package:
  image: ${GO_IMAGE}
  stage: package
  dependencies:
    - silo-build
  script:
    - docker build --build-arg IMAGE=$CENTOS_IMAGE . -t $REGISTRY/$ORG/silo:$VERSION
    - docker push $REGISTRY/$ORG/silo:$VERSION
  only:
    - master
    - tags
