# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# CENTOS_IMAGE
# CI_COMMIT_TAG
# DOCKER_IMAGE
# DIND
# DOCKER_USER
# DOCKER_PASS
# REGISTRY
# ORG

variables:
  IMAGE_PREFIX: "silo"

image: ${DOCKER_IMAGE}

services:
  - ${DIND}

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $REGISTRY

stages:
  - package

silo:
  stage: package
  script:
    - go build -o silo main.go
    - docker build --build-arg IMAGE=$CENTOS_IMAGE . -t $REGISTRY/$ORG/silo:$VERSION
    - docker push $REGISTRY/$ORG/silo:$VERSION
  only:
    - master
    - tags
