sudo: required

language: go

services:
  - docker

install:
  - go get github.com/ngageoint/seed-common/...

script:
   - echo "skipping tests"
   - .build-silo.sh
   - go test .

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never
