sudo: required

language: go

services:
  - docker

matrix:
  include:
    - os: linux
      addons:
        postgresql: "9.5"
        apt:
          packages:
            - postgresql-9.5-postgis-2.3

install:
  - go get github.com/ngageoint/seed-common/...

env:
   - DATABASE_URL=postgis://postgres:@localhost:5432/test_silo?sslmode=disable

script:
   - ./build-silo.sh
   - psql -c 'create database test_silo;' -U postgres
   - go test ./...

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never
